# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: bolt
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  namespace: bolt
  name: slack-secret
  labels:
    app: bolt
data:
  SLACK_OAUTH_TOKEN: <slack_oauth_token_base64>
  SLACK_SIGNIN_SECRET: <slack_signin_secret_base64>
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bolt
  name: bolt-storage
  labels:
    app: bolt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bolt
  name: bolt
  labels:
    app: bolt
data:
  DONT_JOIN_AFTER: "17:30"
  DONT_JOIN_AFTER_TZ: "Asia/Jerusalem"
  ADMIN_SLACK_USER_IDS: "<slack_user_id>[,<slack_user_id>...]"
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bolt
  name: bolt
  labels:
    app: bolt
spec:
  selector:
    matchLabels:
      app: bolt
      tier: web
  template:
    metadata:
      labels:
        app: bolt
        tier: web
    spec:
      containers:
        - name: bolt-app
          image: oriser/bolt
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: slack-secret
            - configMapRef:
                name: bolt
          volumeMounts:
            - name: sqlite-storage
              mountPath: /var/sqlite
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: bolt-storage
---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: bolt
  name: bolt
  labels:
    app: bolt
spec:
  selector:
    app: bolt
    tier: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "<static_ip>"